# frozen_string_literal: true
source 'https://rubygems.org'

# Specify your gem's dependencies in sleipnir.gemspec
gemspec
gem 'rubocop', github: 'nelsonjr/rubocop', branch: 'feature/ignore-parent-exclude'
